### ISSUE TITLE
Why OCRNet is worse than DeepLabv3 in table 5.

### ISSUE THREAD

**Issue by EricKani** [CharlesPikachu/mcibi#3]
Or why you choose DeepLabv3 as your structure not other latest structure in your experiments? Maybe it can hit a higher score.
Just confused.

Thank you~

**Comment by CharlesPikachu** [comment]
(1) Why OCRNet is worse than DeepLabv3
In our re-implementation (refer to https://github.com/SegmentationBLWX/sssegmentation), Deeplabv3 baseline (45.16%) is much better than OCRNet baseline (43.99%), under the same training settings (e.g., backbone, iterations, to name a few). 
(2) why you choose DeepLabv3 as your structure not other latest structure in your experiments
You are right, other latest structure (e.g., upernet, deeplabv3plus) can help our method hit a higher score. But deeplabv3 is good enough in our view.

**Comment by EricKani** [comment]
I get you. 
You mean your reimplementation of DeepLabv3 is better than OCRNet in Table 5.
But I find there are some situations that OCRNet performs better than DeepLabv3, e.g. in Table 7.
Is that means OCRNet is not a robust structure as a newer method? In fact, OCRNet and DeepLabv3 perform comparably?

And BTW, are the scores in the tables are copied from original papers, or reimplemented by yourself?

Best

**Comment by CharlesPikachu** [comment]
Table 1-5 is used for ablation study, so all the reported scores are the reimplemented  results for a fair comparison.

In Table 6-9, the reported scores of other methods are copied from original papers.

This is a common practice.

**Comment by EricKani** [comment]
Thanks for your patient response. It's a great work!
