### ISSUE TITLE
Memory model 一些问题

### ISSUE THREAD

**Issue by qdd1234** [CharlesPikachu/mcibi#4]
您好，您在memory.py里面写了update这个函数，但是这个函数我没有看到调用，我想问一下您这么update具体是怎么调用的，谢谢

**Comment by CharlesPikachu** [comment]
在这调用了：https://github.com/CharlesPikachu/mcibi/blob/main/src/models/memorynet/memorynet.py#L168

**Comment by qdd1234** [comment]
您好，如果进入测试环节或者训练时候的验证环节，target为None，这怎么update memory?

**Comment by qdd1234** [comment]
您是否可以提供一下模型推理的代码，谢谢

**Comment by CharlesPikachu** [comment]
完整代码在README里写了，合并在了https://github.com/SegmentationBLWX/sssegmentation ，inference阶段不更新memory
