### ISSUE TITLE
关于mt更新机制的问题

### ISSUE THREAD

**Issue by mymuli** [CharlesPikachu/mcibi#5]
你好，我发现论文**公式(7)中mt**的更新和**代码中mt**的更新机制好像不一样。
https://github.com/CharlesPikachu/mcibi/blob/62dfe509b34e771b037fea778b1fd2a9a3d78bc2/src/models/memorynet/memory.py#L158

请问一下，论文的实验结果是采用代码中的机制呢？

**Comment by CharlesPikachu** [comment]
learning_rate是poly更新的

**Comment by mymuli** [comment]
> learning_rate是poly更新的

理解了，谢谢！
